export const FETCH_MEMBERS_START   = "FETCH_MEMBERS_START";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAIL    = "FETCH_MEMBERS_FAIL";

export const CREATE_MEMBER_START   = "CREATE_MEMBER_START";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_FAIL    = "CREATE_MEMBER_FAIL";

export const UPDATE_MEMBER_START   = "UPDATE_MEMBER_START";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAIL    = "UPDATE_MEMBER_FAIL";

export const FETCH_CLASSES_START   = "FETCH_CLASSES_START";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAIL    = "FETCH_CLASSES_FAIL";

export const CREATE_CLASS_START   = "CREATE_CLASS_START";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL    = "CREATE_CLASS_FAIL";

export const UPDATE_CLASS_START   = "UPDATE_CLASS_START";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAIL    = "UPDATE_CLASS_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
